import React from "react";
import Head from "next/head";
import Editor from "@/components/editor/Editor";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Web Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-4 sm:px-8 pb-20 pt-10">
        <Editor />
      </main>
    </React.Fragment>
  );
}